-- Search query log table for debugging and analysis.
-- Records every hybrid search explain request with full BM25, semantic and RRF results.

CREATE TABLE search_query_log (
    id                  NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY PRIMARY KEY,

    -- Request context
    query               VARCHAR2(2000)   NOT NULL,
    index_name          VARCHAR2(255)    NOT NULL,
    search_type         VARCHAR2(50)     DEFAULT 'HYBRID_EXPLAIN' NOT NULL,

    -- Timing (ms)
    took_ms             NUMBER,
    bm25_took_ms        NUMBER,
    semantic_took_ms    NUMBER,

    -- Settings snapshot (weights, k, RRF constant)
    bm25_weight         NUMBER(5,4),
    semantic_weight     NUMBER(5,4),
    rank_constant       NUMBER,
    candidate_limit     NUMBER,
    result_limit        NUMBER,

    -- Result counts
    bm25_result_count   NUMBER,
    semantic_result_count NUMBER,
    final_result_count  NUMBER,
    total_candidates    NUMBER,

    -- Full JSON payloads for deep inspection
    bm25_results_json      CLOB,   -- [{rank, score, id, title, ...}]
    semantic_results_json  CLOB,   -- [{rank, score, id, title, ...}]
    final_results_json     CLOB,   -- [{rank, rrfScore, bm25Rank, semanticRank, ...}]
    settings_json          CLOB,   -- full HybridSettings snapshot

    -- Error tracking
    error_message       CLOB,
    status              VARCHAR2(20) DEFAULT 'SUCCESS' NOT NULL,  -- SUCCESS | ERROR

    -- Timestamps
    created_at          TIMESTAMP WITH TIME ZONE DEFAULT SYSTIMESTAMP NOT NULL
);

CREATE INDEX idx_sql_query    ON search_query_log (query);
CREATE INDEX idx_sql_created  ON search_query_log (created_at DESC);
CREATE INDEX idx_sql_status   ON search_query_log (status);
CREATE INDEX idx_sql_index    ON search_query_log (index_name);
